### PR TITLE
fix(refactor): just cleaning unused files

### PR DESCRIPTION
**Pull request by syukronarie**
- this file is not used anymore

### CODE REVIEW

**Review by TaksaWibawa — CHANGES_REQUESTED** [review]
hapus lagi mas

**Review by indrakurr — COMMENTED** [review]
test

**Comment by badebess** [comment]
test review saja

**Comment by anggasptr** [comment]
test

**Comment by SanH16** [comment]
tes review

**Review by aaaroz — COMMENTED** [review]
ok

**Review by nflnsr — APPROVED** [review]
infokan

**Comment by FelicioAngga** [comment]
hmm

**Pull request closed without merging**
